### ISSUE TITLE
Support for logstash 8.X version

### ISSUE THREAD

**Issue by da-head0** [DataDog/logstash-output-datadog_logs#32]
**Describe what happened:**
In datadog-logstash integration, the compability[https://docs.datadoghq.com/integrations/logstash/#compatibility] is with Logstash 5.x, 6.x and 7.x versions.

**Describe what you expected:**
I wonder when Logstash 8.X version is available for datadog integration. 

Thanks.

**Steps to reproduce the issue:**

**Additional environment details (Operating System, Cloud provider, etc):**

**Comment by jseigman-apex** [comment]
This would be awesome to get this plugin working for Logstash 8.X as we currently are not able to have both the google bigquery plugin which requires 8.5 and this plugin simultaneously.

**Comment by remeh** [comment]
👋 

While we document supporting `5.x`, `6.x` and `7.x`, I've just successfully used the datadog-logstash plugin with `logstash 8.6.2` (with JRuby 9.3.1.0 and OpenJDK 17) to collect and send logs to Datadog.

I'll change the documentation accordingly but you should be good using Logstash 8.X with the datadog-logstash integration. Let me know if you have a different experience.

**Comment by remeh** [comment]
Closing following the merge of #38
